/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rdict.h"

bool_t
xdr_dictionary (XDR *xdrs, dictionary *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->word, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->meaning, ~0))
		 return FALSE;
	return TRUE;
}
