/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RDICT_H_RPCGEN
#define _RDICT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct dictionary {
	char *word;
	char *meaning;
};
typedef struct dictionary dictionary;

#define RDICTPROG 0x30090949
#define RDICTVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define INSERTW 1
extern  char ** insertw_1(dictionary *, CLIENT *);
extern  char ** insertw_1_svc(dictionary *, struct svc_req *);
#define DELETEW 2
extern  char ** deletew_1(char **, CLIENT *);
extern  char ** deletew_1_svc(char **, struct svc_req *);
#define LOOKUPW 3
extern  char ** lookupw_1(char **, CLIENT *);
extern  char ** lookupw_1_svc(char **, struct svc_req *);
extern int rdictprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INSERTW 1
extern  char ** insertw_1();
extern  char ** insertw_1_svc();
#define DELETEW 2
extern  char ** deletew_1();
extern  char ** deletew_1_svc();
#define LOOKUPW 3
extern  char ** lookupw_1();
extern  char ** lookupw_1_svc();
extern int rdictprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_dictionary (XDR *, dictionary*);

#else /* K&R C */
extern bool_t xdr_dictionary ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RDICT_H_RPCGEN */
