/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rdict.h"
#define HASHSIZE 101



struct hlist { /* table entry: */
    struct hlist *next; /* next entry in chain */
    char *name; /* defined name */
    char *defn; /* replacement text */
};

static struct hlist *hashtab[HASHSIZE]; /* pointer table */

/* hash: form hash value for string s */
unsigned hash(char *s)
{
    unsigned hashval;
    for (hashval = 0; *s != '\0'; s++)
      hashval = *s + 31 * hashval;
    return hashval % HASHSIZE;
}

/* lookup: look for s in hashtab */
struct hlist *lookup(char *s)
{
    struct hlist *np;
    for (np = hashtab[hash(s)]; np != NULL; np = np->next)
        if (strcmp(s, np->name) == 0)
          return np; /* found */
    return NULL; /* not found */
}

char *string_dup(char *);
/* install: put (name, defn) in hashtab */
struct hlist *install(char *name, char *defn)
{
    struct hlist *np;
    unsigned hashval;
    if ((np = lookup(name)) == NULL) { /* not found */
        np = (struct hlist *) malloc(sizeof(*np));
        if (np == NULL || (np->name = string_dup(name)) == NULL)
          return NULL;
        hashval = hash(name);
        np->next = hashtab[hashval];
        hashtab[hashval] = np;
    } else /* already there */
        free((void *) np->defn); /*free previous defn */
    if ((np->defn = string_dup(defn)) == NULL)
       return NULL;
    return np;
}

char *string_dup(char *s) /* make a duplicate of s */
{
    char *p;
    p = (char *) malloc(strlen(s)+1); /* +1 for ’\0’ */
    if (p != NULL)
       strcpy(p, s);
    return p;
}


/* remove_name name, defn in hashtab */
struct hlist *remove_name(char *name)
{
    struct hlist *prev;
    struct hlist *curr;

    unsigned hashval;

    hashval = hash(name);
    curr = hashtab[hashval];
    prev = NULL;

    for(; curr != NULL; curr = curr->next){
        if(strcmp(curr->name, name) == 0){
            if(prev == NULL){
                hashtab[hashval] = curr->next;
            } else {
                prev->next = curr->next;
            }
            return curr; 
        }
        prev = curr;
    }
    return NULL;
 }


/*------------------------------------------------------------------------
 * insertw_1_svc - insert  a word and it meaning in the dictionary
 *------------------------------------------------------------------------
 */


char **
insertw_1_svc(dictionary *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
	struct hlist *dict = install(argp->word, argp->meaning);
	if (dict != NULL) {
		result = dict->name;
	} else{
		result = "";
	}

	return &result;
}


/*------------------------------------------------------------------------
 * lookupw - look up a word in the dictionary
 *------------------------------------------------------------------------
 */


char **
lookupw_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

        struct hlist *dict = lookup(*argp);
	if (dict != NULL){
		result = dict->defn;
	} else {
		result = "";
	}
	return &result;
}



/*------------------------------------------------------------------------
 * deletew_1_svc - delete  a word from the dictionary
 *------------------------------------------------------------------------
 */

char **
deletew_1_svc(char **argp, struct svc_req *rqstp)
{
	static char *  result;

	/*
	 * insert server code here
	 */
        struct hlist *dict = remove_name(*argp);
	if (dict != NULL){
		result = dict->defn;
	} else {
		result = "";
	}
	return &result;
}


